on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v2
      - run: pip install pylint
      - run: find . -name "*.py" -exec pylint --rcfile=.pylintrc  --exit-zero {} +

  vulns_checks:
    runs-on: ubuntu-latest
    name: Vulnerabilities check
    steps:
      - uses: actions/checkout@v2
      - run: pip install bandit
      - run: bandit . -r

  code_coverage:
    runs-on: ubuntu-latest
    name: Code Coverage
    steps:
      - name: Generate Report
      - run: pip install coverage
      - run: coverage run -m pytest -vv
      - name: Upload Coverage to Codecov
      - uses: codecov/codecov-action@v1


