on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
      - uses: actions/checkout@v2
      - run: pip install pylint
      - run: find . -name "*.py" -exec pylint --exit-zero {} +