on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
      - uses: actions/checkout@v2
      - run: pip install pylint
      - run: pwd && find . || echo $?
      - run: pylint browser.py || echo $?
      - run: pylint *.py || echo $?
      - run: find . -name "*.py" -exec pylint {} + || echo $?