on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - run: pip install pylint 
    - run: pylint browser.py || echo $?
    - run: pylint *.py || echo $?
    - run: find . -name "*.py" -exec pylint {} + || echo $?