on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - run: pip install pylint pylint-exit
    - run: pylint || pylint-exit $?
    - run: pylint browser.py || pylint-exit $?
    - run: pylint *.py || pylint-exit $?
    - run: find . -name "*.py" -exec pylint {} + || pylint-exit $?